trigger:
- main

pr:
  autoCancel: true
  branches:
    include:
    - main

variables:
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
  MAVEN_OPTS: '-ntp -B -Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'

stages:
- stage: build
  jobs:
  - job: compile-linux
    pool: vmssagentspool
    steps:
    - template: compile.yml
      parameters:
        jdkDirectory: '/usr/lib/jvm/java-11-openjdk-amd64'
        jdkVersionOption: '1.11'
  - job: test-java8
    displayName: 'Test with Java 8'
    pool: vmssagentspool
    steps:
    - template: test.yml
      parameters:
        jdkDirectory: '/usr/lib/jvm/java-8-openjdk-amd64'
        jdkVersionOption: '1.8'
    dependsOn: compile-linux
  - job: test-java11
    displayName: 'Test with Java 11'
    pool: vmssagentspool
    steps:
    - template: test.yml
      parameters:
        jdkDirectory: '/usr/lib/jvm/java-11-openjdk-amd64'
        jdkVersionOption: '1.11'
    dependsOn: compile-linux
